_sass/_buttons.scss, _sass/_homepage.scss, _sass/_mixins.scss, _sass/_table.scss, _sass/_type.scss, _sass/_variables.scss, css/elaconf.scss, index.html
=> adds "Tickets" section

_sass/_homepage.scss, _sass/_layout.scss, _sass/_pages.scss, _sass/_type.scss, index.html, talk-inspiration/index.md, talk-inspiration/timeline.svg
Getting this big push staged, here’s what’s happening:
* Adds section “What’s Included” to list out what’s included in the ticket price &mdash; @jonitrythall would love some help on filling out copy
* Adds section “Call for speakers” with links to the lightning and talk forms 
* Adds new page “Talk inspiration”
* Adds public transit information under “Venue” section &mdash; would love extra :eyes: to make sure I got this info right
/cc @jonitrythall @leekinney @dominiqueclarke
=> Adds: what's included, CFP, talk inspiration, public transit

_config.yml, _layouts/default.html, _sass/_newsletter.scss, css/elaconf.scss
Switch from Tinyletter to Mailchimp signup.
=> Mailchimp Update

index.html
@leekinney I added the hotel information to the “Venue” section and updated the map to include the hotel. Does everything look accurate/ok?
=> adds hotel information

images/timeline.svg, index.html, talk-inspiration/index.md, talk-inspiration/timeline.svg
per our meeting last week and chat, I updated the timelines to push the deadline dates back a week and a half
This will give us time to hold office hours.
I also removed the note about early
bird tickets being available.
=> Pushed back submission and notification date

index.html
=> removes links to submit a talk

index.html
Remove CFP to move up Speaker Spotlight
=> [merge on 10/17] removes CFP section

agenda/_posts/2015-11-21-career-change.md
followed the readme instructions - wasn't sure I understood where the session abstract belongs.
=> change career-change title and description

volunteer/index.md
=> adds time keeper volunteer position

_config.yml, _sass/_layout.scss, index.html, proposals/index.md, sponsorship-packages/index.md, talk-inspiration/index.md
Home page:
Call for Proposals page:
cc @ajpeddakotla @jonitrythall @leekinney 
fix #41
=> add call for proposals

_includes/footer.html, _includes/header.html, _includes/nav.html, _includes/svg/menu.svg, _layouts/page.html, _layouts/speaker.html, _sass/_header.scss, _sass/_layout.scss, _sass/_pages.scss, _sass/_type.scss, sponsor/index.html
First iteration of top navigation
Top nav:
Mobile:
fix #45
=> add top navigation

_data/levels.yml, _data/sponsors.yml, _includes/sponsors.html, _sass/_mixins.scss, _sass/_sponsors.scss, _sass/_type.scss, index.html, sponsor/index.html
=> create sponsor levels

index.html, proposals/index.md
=> [merge 9/15 11:59 pm] remove cfp

_agenda/16-breakout-c.md, _agenda/16-breakout-d.md, _agenda/18-breakout-b.md, _agenda/18-breakout-d.md, _layouts/agenda.html, _layouts/speaker.html, agenda/index.html, index.html
=> Adds moderators!

_includes/tickets.html, grant/index.md
* Removes link to grant application from under ticket widget
* Adds “Grant applications are now closed. Thank you for your interest!“ to /grant page
=> close grant application

_sass/_jobs.scss, jobs/index.md
=> adds github jobs

_data/levels.yml, _data/sponsors.yml, _includes/sponsors.html, _sass/_sponsors.scss, test/ela.test.js
=> add individual sponsors ✨

_data/sponsors.yml
=> add individuals from indy hall

_layouts/agenda.html, _sass/_header.scss, index.html
=> [merge Friday] adds speaker feedback button

ama/index.md
=> adds ama page

_config.yml, about/index.md
Refs https://github.com/katydecorah/elaconf/issues/16
=> More inclusive language

_sass/_homepage.scss, index.html
This section is more or less a placeholder. THe content will be updated with MC + Keynote photos/links once we have them, but will still preserve button to CFP and intro text.
=> adds CFP section

index.html
I'll merge this first thing tomorrow morning
=> closes CFP

_includes/tickets.html, _layouts/page.html, _layouts/speaker.html, grants/index.md, index.html, tickets/index.md, volunteer/index.md
(I think the spacing of the widget will be less wonky once the tickets are populated)
=> 2017 tickets

_includes/map.html, index.html
=> adds hotel info, updates map

donate-a-ticket/index.md
fixes https://github.com/katydecorah/elaconf/issues/92
=> adds donate a ticket page

_config.yml, _data/places.yml, _sass/_map.scss, css/elaconf.scss, index.html, local/index.html, local/places.js, test/ela.test.js, venue/index.html
same map, a few new locations!
=> adds philly guide
